const prod = [
  {
    id: 1,
    name: "jeans",
    quantity: 12,
    price: 99,
    image: "https://source.unsplash.com/300x300/weekly/?jeans",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 2,
    name: "t-shirt",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?t-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 3,
    name: "apple",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?apple",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 4,
    name: "iphone",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?iphone",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 5,
    name: "android",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?mobile",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 6,
    name: "macbook",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?macbook",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 7,
    name: "charger",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?charger",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 8,
    name: "earbuds",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?earbuds",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 9,
    name: "earphone",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?earphone",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 10,
    name: "top",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?top",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: 11,
    name: "lower",
    quantity: 122,
    price: 939,
    image: "https://source.unsplash.com/300x300/weekly?lower",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex possimus ipsum aut rem assumenda expedita minus eum aliquid eius modi molestias necessitatibus consectetur, accusamus sequi, nesciunt tempora laudantium dicta quod.",
  },
  {
    id: "1",
    name: "test-2",
    quantity: "1",
    price: "12",
    image: "https://source.unsplash.com/300x300/?girls",
    desc: "AXSzcv",
  },
];

module.exports = prod;
